### ISSUE TITLE
NotImplementedError: ConfigDrive is not supported on this platform: freebsd10

### ISSUE THREAD

**Issue by supporthk** [pellaeon/bsd-cloudinit#25]
Hi,

I tried to run this with Nocloud ConfigDrive but it thorows the error "ConfigDrive is not supported on this platform: freebsd10"...when it should be available.. ??

Or is there anybody can suggest the workaround for it..

**Comment by iblis17** [comment]
Hi @supporthk 
There is a [work in progress](https://github.com/pellaeon/bsd-cloudinit/pull/24). 
You can try it out first.
We are testing it.

**Comment by supporthk** [comment]
Hi iblis17,

Thanks for the udpates..i will try it first and let you know my findings and issue..

**Comment by supporthk** [comment]
Hi,

I tried to use this one and got the following error :- 

-----------------
2016-03-10 15:02:52.461 697 ERROR cloudbaseinit.metadata.factory [-] Failed to load metadata service 'cloudbaseinit.metadata.services.configdrive.ConfigDriveService'
2016-03-10 15:02:52.461 697 ERROR cloudbaseinit.metadata.factory [-] ConfigDrive is not supported on this platform: freebsd10
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory Traceback (most recent call last):
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory   File "/usr/local/bsd-cloudinit/cloudbaseinit/metadata/factory.py", line 50, in get_metadata_service
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory     if service.load():
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory   File "/usr/local/bsd-cloudinit/cloudbaseinit/metadata/services/configdrive.py", line 53, in load
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory     mgr = factory.get_config_drive_manager()
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory   File "/usr/local/bsd-cloudinit/cloudbaseinit/metadata/services/osconfigdrive/factory.py", line 29, in get_config_drive_manager
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory     'this platform: %s' % sys.platform)
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory NotImplementedError: ConfigDrive is not supported on this platform: freebsd10
2016-03-10 15:02:52.461 697 TRACE cloudbaseinit.metadata.factory
2016-03-10 15:02:52.462 697 CRITICAL cloudbaseinit [-] CloudbaseInitException: No available service found
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit Traceback (most recent call last):
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit   File "/usr/local/bsd-cloudinit/run.py", line 3, in <module>
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit     shell.main()
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit   File "/usr/local/bsd-cloudinit/cloudbaseinit/shell.py", line 29, in main
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit     init.InitManager().configure_host()
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit   File "/usr/local/bsd-cloudinit/cloudbaseinit/init.py", line 100, in configure_host
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit     service = metadata_factory.get_metadata_service()
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit   File "/usr/local/bsd-cloudinit/cloudbaseinit/metadata/factory.py", line 55, in get_metadata_service
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit     raise exception.CloudbaseInitException("No available service found")
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit CloudbaseInitException: No available service found
2016-03-10 15:02:52.462 697 TRACE cloudbaseinit
2016-03-10 15:39:48.381 822 ERROR cloudbaseinit.init [-] plugin 'NetworkConfigPlugin' failed with error 'coercing to Unicode: need string or buffer, NoneType found'
2016-03-10 15:39:48.383 822 ERROR cloudbaseinit.init [-] coercing to Unicode: need string or buffer, NoneType found
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init Traceback (most recent call last):
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init   File "/usr/local/bsd-cloudinit/cloudbaseinit/init.py", line 67, in _exec_plugin
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init     shared_data)
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init   File "/usr/local/bsd-cloudinit/cloudbaseinit/plugins/freebsd/networkconfig.py", line 68, in execute
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init     gateway, dnsdomain, dnsnameservers)
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init   File "/usr/local/bsd-cloudinit/cloudbaseinit/osutils/freebsd.py", line 79, in set_static_network_config
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init     if_cmd = 'ifconfig ' + adapter_name + ' inet ' + address + ' netmask ' + netmask + ' broadcast ' + broadcast
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init TypeError: coercing to Unicode: need string or buffer, NoneType found
2016-03-10 15:39:48.383 822 TRACE cloudbaseinit.init
2016-03-10 15:39:48.824 822 ERROR cloudbaseinit.init [-] plugin 'EnlargeRoot' failed with error 'Command 'growfs -y /dev/vtbd0p2' returned non-zero exit status 1'
2016-03-10 15:39:48.825 822 ERROR cloudbaseinit.init [-] Command 'growfs -y /dev/vtbd0p2' returned non-zero exit status 1
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init Traceback (most recent call last):
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init   File "/usr/local/bsd-cloudinit/cloudbaseinit/init.py", line 67, in _exec_plugin
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init     shared_data)
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init   File "/usr/local/bsd-cloudinit/cloudbaseinit/plugins/freebsd/enlargeroot.py", line 32, in execute
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init     self._call_shell('growfs -y /dev/' + rootdisk + 'p' + partition)
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init   File "/usr/local/bsd-cloudinit/cloudbaseinit/plugins/freebsd/enlargeroot.py", line 12, in _call_shell
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init     return subprocess.check_call(cmd, stderr=subprocess.STDOUT, shell=True)
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init   File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init     raise CalledProcessError(retcode, cmd)
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init CalledProcessError: Command 'growfs -y /dev/vtbd0p2' returned non-zero exit status 1
2016-03-10 15:39:48.825 822 TRACE cloudbaseinit.init
2016-03-10 15:39:48.830 822 WARNING cloudbaseinit.plugins.common.userdatautils [-] Unsupported user_data format
----------------

My configdrive data is as below :- 
config-2
config-2 >>openstack
config-2 >>openstack >>content>>network_config
---------------
iface vtnet0 inet static
  address 10.10.0.5
  netmask 255.255.255.0
  gateway 10.10.0.1
  dns-nameservers 8.8.8.8

iface vtnet1 inet static
  address 20.10.0.106
  netmask 255.255.255.0
------------------

config-2 >>openstack >>latest>>meta.json
---------
{"hostname": "vm1", "launch_index": 0, "network_config": {"content_path": "/content/network_config"}}
---------
config-2 >>openstack >>latest>>user_data (Blank)

Thanks,
Punit

**Comment by kense2660** [comment]
Hello,

We're having the same issue. Is there any update on this issue?
